# Generated by Django 4.1.7 on 2023-08-06 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='Liked_On',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 7, 0, 27, 55, 340608)),
        ),
    ]
